### ISSUE TITLE
catch exception when elasticsearch is not available

### ISSUE THREAD

**Issue by itayB** [itayB/elasticsearch-metadata#18]
Running in docker without Elasticsearch up, end up with: 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/server/handlers/get_indices_handler.py", line 25, in get_indices_handler
    indices: List[Dict] = await _get_request(es_url + '/_cat/indices?format=json')
  File "/server/handlers/get_indices_handler.py", line 8, in _get_request
    async with session.get(url) as response:
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 480, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 980, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 943, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:9200 ssl:default [Address not available]
```

**Comment by itayB** [comment]
+ use https://material-ui.com/components/snackbars/#customized-snackbars in UI
